services:
  db:
    image: postgres:17-alpine
    container_name: catfoodstore_postgres
    env_file:
      - ./catfoodstore_db/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./catfoodstore_db/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: ./catfoodstore_backend
      dockerfile: Dockerfile
    container_name: catfoodstore_backend
    env_file:
      - ./catfoodstore_backend/.env
    expose:
      - "8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./catfoodstore-app
      dockerfile: Dockerfile
    container_name: catfoodstore_frontend
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: catfoodstore_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./catfoodstore-app/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
